### ISSUE TITLE
Typo: "wait up steering" should be "wake up steering"

### ISSUE THREAD

**Issue by mr-canoe-head** [JC-Concepts/RGT-Arduino_USB_Steer#1]
Noticed a minor typo in your comment here:

https://github.com/JC-Concepts/RGT-Arduino_USB_Steer/blob/a11d26381c688020cc7756799d3627fd7d948808/HID_RGT_Pullup.ino#L29

I think it should read `wake` up steering instead of `wait`.

**Comment by JC-Concepts** [comment]
No need anymore... RGT is dead 👎
